In [1]:
import tensorflow as tf
import numpy as np

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
t = tf.constant([
    [[1, 1, 1], [2, 2, 2]],
    [[3, 3, 3], [4, 4, 4]],
    [[5, 5, 5], [6, 6, 6]]]
)

In [5]:
t.shape

TensorShape([Dimension(3), Dimension(2), Dimension(3)])

In [9]:
with tf.Session() as sess:
     print(sess.run(tf.slice(t, [1, 0, 0], [1, 1, 3])))

[[[3 3 3]]]


In [10]:
s = tf.constant([[1,2,3]])
s.shape

TensorShape([Dimension(1), Dimension(3)])

In [15]:
with tf.Session() as sess:
    print(sess.run(s))
    print(sess.run(tf.squeeze(s, 0)))

[[1 2 3]]
[1 2 3]


In [19]:
import tensorflow as tf

tf.reset_default_graph()

#Define input feature columns
feature_columns = [tf.feature_column.numeric_column("sq_footage")]

#Instantiate Linear Regression Model
estimator = tf.estimator.LinearRegressor(
    feature_columns=feature_columns)

#Train
def input_fn_train():
    feature_data = {"sq_footage": tf.constant([1000,2000])}
    label_data = tf.constant([100000,200000])
    return feature_data, label_data

estimator.train(input_fn=input_fn_train, steps=100)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_service': None, '_session_config': None, '_is_chief': True, '_task_id': 0, '_tf_random_seed': None, '_train_distribute': None, '_save_summary_steps': 100, '_task_type': 'worker', '_keep_checkpoint_max': 5, '_save_checkpoints_steps': None, '_keep_checkpoint_every_n_hours': 10000, '_global_id_in_cluster': 0, '_save_checkpoints_secs': 600, '_master': '', '_log_step_count_steps': 100, '_num_ps_replicas': 0, '_model_dir': '/var/folders/8_/svks8q1d03s882pk945z2p0000hm6n/T/tmpuolode0q', '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x127569dd8>, '_evaluation_master': '', '_num_worker_replicas': 1}
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 1 into /var/folders/8_/

In [23]:
#Predict
def input_fn_pred():
    feature_data = {"sq_footage": tf.constant([1500, 1500])}
    feature_dataset = tf.data.Dataset.from_tensors(feature_data)
    return feature_dataset

list(estimator.predict(input_fn=input_fn_pred))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/8_/svks8q1d03s882pk945z2p0000hm6n/T/tmpuolode0q/model.ckpt-100
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([5541.9365], dtype=float32)},
 {'predictions': array([5541.9365], dtype=float32)}]

In [24]:
# Creates a graph.
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)

# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

# Runs the op.
print(sess.run(c))

[[22. 28.]
 [49. 64.]]
